platform:ios, ‘8.0’
use_frameworks!

target 'MShare' do
    pod 'GoogleAPIClient/Drive', '~> 1.0.2'
pod 'GTMOAuth2', '~> 1.1.0'
pod 'box-ios-sdk'
pod 'OneDriveSDK'
pod 'Dropbox-iOS-SDK'
pod 'Firebase'
pod 'Firebase/Database'
pod 'FirebaseUI'
pod 'MBProgressHUD'
pod 'Intercom'
pod 'SwiftyJSON'
end
